[usage_debugFlag]
other = "dump debugging info to stdout"

[usage_concurrency]
other = "specify number of concurrent threads/workers"

[Err_SinglePairCredQty]
other = "Single credential-pair stuffing requires *two* parameters only"

[Err_UnableToLoadManifest]
other = "Unable to load manifests. (Reason ::: {{.Error}})"

[Err_UnableToParseResponseData]
other = "Unable to parse response body. (Reason ::: {{.Error}})"
