[usage_debugFlag]
other = "dump debugging info to stdout"

[usage_concurrency]
other = "specify number of concurrent threads/workers"

[Err_SinglePairCredQty]
other = "Single credential-pair stuffing requires *two* parameters only"
